import { Geist, Tomorrow } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/nav.jsx";
import FooterSection from "@/components/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const tomorrow = Tomorrow({
  variable: "--font-tomorrow",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

{
  /* <body
className={`${geistSans.variable} antialiased`}
>
{children}
</body> */
}

export const metadata = {
  title: "Nafiz Dev | Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={tomorrow.className}>
        <Navbar />
        <hr className="text-lightblue max-w-[1400px] mx-auto" />
        {children}

        <FooterSection />
      </body>
    </html>
  );
}
